name: Build


on:
    workflow_dispatch:
    push:

jobs:
    build:
        name: ${{ matrix.arch }} build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch:
                - x86_64
                - aarch64_cortex-a53
    
        steps:
        - name: Building packages
          uses: actions/checkout@main
          with:
           fetch-depth: 0

        - name: Build
          uses: openwrt/gh-action-sdk@main
          env:
              ARCH: ${{ matrix.arch }}

        - name: Store packages
          uses: actions/upload-artifact@main
          with:
           name: ${{ matrix.arch}}-packages
           path: bin/packages/${{ matrix.arch }}/packages/*.ipk