name: Build


on:
    workflow_dispatch:
    push: 


jobs:
    build:
        name: ${{ matrix.arch }} build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch:
                - x86_64
                - aarch64_cortex-a53
    
        steps:
        - name: Building packages
          uses: actions/checkout@main
          with:
           path: './applications'
           fetch-depth: 0

        - name: Build1
          uses: openwrt/gh-action-sdk@main
          env:
              ARCH: ${{ matrix.arch }}-openwrt-22.03
              FEEDNAME: packages_ci
              PACKAGES: cdnspeedtest
              NO_REFRESH_CHECK: true

        # - name: Build2
        #   uses: openwrt/gh-action-sdk@main
        #   env:
        #       ARCH: ${{ matrix.arch }}-openwrt-22.03
        #       FEEDNAME: packages_ci
        #       PACKAGES: luci-app-cloudflarespeedtest
        #       NO_REFRESH_CHECK: true

        - name: Store packages
          uses: actions/upload-artifact@main
          with:
           name: ${{ matrix.arch}}-packages
           path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

        - name: Delete workflow runs
          uses: AoThen/delete-workflow-runs@main
          with:
                retain_days: 1
                keep_minimum_runs: 5